pipeline:
  test:
    image: node:latest
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn
  tar:
    image: node:latest
    commands:
      tar -zpcv -f a.tar.gz .
    when:
      status: [ success ]
  